services:
  backend1:
    build:
      context: ./api-mock
      dockerfile: Dockerfile
    container_name: backend1
    environment:
      - APP_VERSION=version:1.0.0
  backend2:
    build:
      context: ./api-mock
      dockerfile: Dockerfile
    container_name: backend2
    environment:
      - APP_VERSION=version:2.0.0
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-nats
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - BACKEND1_URL=http://backend1:8080
      - BACKEND2_URL=http://backend2:8080
  nats:
    image: nats-streaming:latest
    container_name: server-nats
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222      
  suscriptor:
    build:
      context: ./nats-client
      dockerfile: Dockerfile
    container_name: suscriptor-nats
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222